# Generated by Django 4.1.1 on 2022-10-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rpassword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
