# Generated by Django 4.1.1 on 2022-10-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_user_rpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rpassword',
            new_name='reenter_password',
        ),
    ]
